package:
  name: cctk
  version: "1.0"

source:
  git_rev: "main"
  git_url: "https://github.com/Alan-Collins/CRISPR_comparison_toolkit.git"

requirements:
  host:
    - python
    - pip
    - setuptools
    - matplotlib
    - bioconda::dendropy

  run:
    - python
    - matplotlib
    - bioconda::dendropy


about:
  home: https://github.com/Alan-Collins/CRISPR_comparison_toolkit
