package:
  name: cctk
  version: "1.0"

source:
  git_rev: "main"
  git_url: "https://github.com/Alan-Collins/CRISPR_comparison_toolkit.git"
  git_depth: 1

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - matplotlib
    - bioconda::dendropy
    - bioconda::minced


about:
  home: https://github.com/Alan-Collins/CRISPR_comparison_toolkit
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  license_url: https://www.gnu.org/licenses/gpl-3.0.en.html
  summary: Tools to identify and compare CRISPR arrays.
