package:
  name: cctk_dev
  version: "0.2.3"

source:
  # path: ../
  git_rev: "dev"
  git_url: "https://github.com/Alan-Collins/CRISPR_comparison_toolkit.git"
  git_depth: 1

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools

  run:
    - python >=3.7
    - numpy
    - matplotlib
    - bioconda::dendropy
    - bioconda::minced
    - bioconda::blast

about:
  home: https://github.com/Alan-Collins/CRISPR_comparison_toolkit
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  license_url: https://www.gnu.org/licenses/gpl-3.0.en.html
  summary: Tools to identify and compare CRISPR arrays.
