package:
  name: cctk
  version: "1.0"

source:
  git_rev: "main"
  git_url: "https://github.com/Alan-Collins/CRISPR_comparison_toolkit.git"
  git_depth: 1

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - matplotlib
    - bioconda::dendropy
    - bioconda::minced


about:
  home: https://github.com/Alan-Collins/CRISPR_comparison_toolkit
  license_file: LICENSE
  summary: "Tools to identify CRISPR arrays and analyze the relationships between them."
